-- dbo.VW_CONCILIACAO_NFE fonte

CREATE OR ALTER     VIEW VW_CONCILIACAO_NFE AS
SELECT 
    xml.CHAVE_ACESSO as chaveAcesso,
    xml.TIPO_NOTA as tipoNota,
    xml.DATA_EMISSAO as dataEmissao,
    xml.CFOP as cfop,
    xml.CNPJ_EMITENTE as cnpjEmitente,
    xml.NOME_EMITENTE as nomeEmitente,
    xml.CPF_CNPJ_DESTINATARIO as cpfCnpjDestinatario,
    xml.NOME_DESTINATARIO as nomeDestinatario,
    xml.NUMERO_NF as numeroNF,
    xml.VALOR_NF as valorNF,
    xml.STATUS_SEFAZ_DESC as statusSefaz,

    -- 🌟 AS NOVAS COLUNAS PUXANDO DA TABELA
    ISNULL(xml.VALOR_ICMS, 0) as valorIcms,
    ISNULL(xml.VALOR_IPI, 0) as valorIpi,
    ISNULL(xml.VALOR_PIS, 0) as valorPis,
    ISNULL(xml.VALOR_COFINS, 0) as valorCofins,
    ISNULL(xml.VALOR_ISS, 0) as valorIss,

    ISNULL(sm0.filial_nome, '00 - NÃO IDENTIFICADA') as filial,
    
    CASE 
        WHEN xml.STATUS_SEFAZ_DESC LIKE '%Cancel%' OR xml.STATUS_SEFAZ_DESC LIKE '%Denegad%' THEN 'Cancelada'
        WHEN (sf1_nfe.F1_CHVNFE IS NOT NULL) OR (sf1_nfse.F1_DOC IS NOT NULL) THEN 'Entrada'
        WHEN (sf2_nfe.F2_CHVNFE IS NOT NULL) OR (sf2_nfse.F2_DOC IS NOT NULL) THEN 'Saída'
        ELSE 'Não lançado'
    END as statusSistema

FROM XML_NFE_CONCILIACAO xml

-- 1. O JOIN COM AS FILIAIS (Agrupado para nunca duplicar, caso haja CNPJs iguais na SYS_COMPANY)
LEFT JOIN (
    SELECT 
        M0_CGC, 
        MAX(CAST(M0_CODFIL AS VARCHAR) + ' - ' + CAST(M0_FILIAL AS VARCHAR)) as filial_nome 
    FROM dbo.SYS_COMPANY
    WHERE D_E_L_E_T_ = ''
    GROUP BY M0_CGC
) sm0 ON xml.CPF_CNPJ_DESTINATARIO COLLATE DATABASE_DEFAULT = sm0.M0_CGC COLLATE DATABASE_DEFAULT

-- 2. ENTRADAS NFE (PRODUTO) - DISTINCT GERA CHAVE ÚNICA
LEFT JOIN (
    SELECT DISTINCT F1_CHVNFE 
    FROM SF1010 
    WHERE D_E_L_E_T_ = '' AND F1_CHVNFE <> ''
) sf1_nfe ON xml.TIPO_NOTA = 'NFE' AND xml.CHAVE_ACESSO COLLATE DATABASE_DEFAULT = sf1_nfe.F1_CHVNFE COLLATE DATABASE_DEFAULT

-- 2.1 ENTRADAS NFSE (SERVIÇO) - DISTINCT E FILTRO NO D_E_L_E_T_ DO FORNECEDOR (SA2)
LEFT JOIN (
    SELECT DISTINCT f1.F1_DOC, a2.A2_CGC
    FROM SF1010 f1
    INNER JOIN SA2010 a2 ON a2.A2_COD = f1.F1_FORNECE AND a2.A2_LOJA = f1.F1_LOJA AND a2.D_E_L_E_T_ = ''
    WHERE f1.D_E_L_E_T_ = ''
) sf1_nfse ON xml.TIPO_NOTA = 'NFSE' 
  AND RIGHT('000000000' + CAST(xml.NUMERO_NF AS VARCHAR(20)), 9) COLLATE DATABASE_DEFAULT = sf1_nfse.F1_DOC COLLATE DATABASE_DEFAULT 
  AND xml.CNPJ_EMITENTE COLLATE DATABASE_DEFAULT = sf1_nfse.A2_CGC COLLATE DATABASE_DEFAULT

-- 3. SAÍDAS NFE (PRODUTO) - DISTINCT GERA CHAVE ÚNICA
LEFT JOIN (
    SELECT DISTINCT F2_CHVNFE 
    FROM SF2010 
    WHERE D_E_L_E_T_ = '' AND F2_CHVNFE <> ''
) sf2_nfe ON xml.TIPO_NOTA = 'NFE' AND xml.CHAVE_ACESSO COLLATE DATABASE_DEFAULT = sf2_nfe.F2_CHVNFE COLLATE DATABASE_DEFAULT

-- 3.1 SAÍDAS NFSE (SERVIÇO) - DISTINCT E FILTRO NO D_E_L_E_T_ DO CLIENTE (SA1)
LEFT JOIN (
    SELECT DISTINCT f2.F2_DOC, a1.A1_CGC
    FROM SF2010 f2
    INNER JOIN SA1010 a1 ON a1.A1_COD = f2.F2_CLIENTE AND a1.A1_LOJA = f2.F2_LOJA AND a1.D_E_L_E_T_ = ''
    WHERE f2.D_E_L_E_T_ = ''
) sf2_nfse ON xml.TIPO_NOTA = 'NFSE' 
  AND RIGHT('000000000' + CAST(xml.NUMERO_NF AS VARCHAR(20)), 9) COLLATE DATABASE_DEFAULT = sf2_nfse.F2_DOC COLLATE DATABASE_DEFAULT 
  AND xml.CNPJ_EMITENTE COLLATE DATABASE_DEFAULT = sf2_nfse.A1_CGC COLLATE DATABASE_DEFAULT

WHERE (
    xml.CFOP NOT IN ('1102', '1202', '1501', '1905', '1949') 
    OR xml.CFOP IS NULL 
    OR xml.CFOP = ''
);